### ISSUE TITLE
ModuleNotFoundError: No module named 'engine'

### ISSUE THREAD

**Issue by shenweima** [PopicLab/cue#16]
an error:
```
python3 ~/scripts/cue/engine/call.py --data_config call_data.yaml --model_config call_model.yaml 
*********************************
*  cue (v0.2.2): discovery mode *
*********************************
[INFO]  ========== Model config ==========
        model_path: /share/home/yzbsl_masw/scripts/cue/data/models/cue.v2.pt
        gpu_ids: []
        n_jobs_per_gpu: 1
        n_cpus: 1
        report_interval: 100
        batch_size: 16
        logging_level: INFO
        signal_set: SV_SIGNAL_SET.SHORT
        class_set: SV_CLASS_SET.BASIC5ZYG
        num_keypoints: 1
        model_architecture: HG
        image_dim: 256
        sigma: 10
        stride: 4
        heatmap_peak_threshold: 0.4
        pretrained_refinenn_path: None
        config_file: call_model.yaml
        experiment_dir: /share/home/yzbsl_masw/data/projects/results/CS2.1/AABBDD/SV_cue
        devices: [device(type='cpu')]
        device: cpu
        log_dir: /share/home/yzbsl_masw/data/projects/results/CS2.1/AABBDD/SV_cue/logs/
        report_dir: /share/home/yzbsl_masw/data/projects/results/CS2.1/AABBDD/SV_cue/reports/
        log_file: /share/home/yzbsl_masw/data/projects/results/CS2.1/AABBDD/SV_cue/logs/main.log
        classes: ['NEG', 'DEL-HOM', 'INV-HOM', 'DUP-HOM', 'DEL-HET', 'INV-HET', 'DUP-HET', 'IDUP-HOM', 'IDUP-HET']
        num_classes: 9
        n_signals: 6
[INFO] ========== Data config =========
        bam: /share/home/yzbsl_masw/data/projects/results/CS2.1/AABBDD/1496A.mrkdup.sorted.cram
        fai: /share/home/yzbsl_masw/data/genomes/ref/Chinese_spring2.1_KN9204_1RS.fasta.fai
        chr_names: chr1A
        logging_level: INFO
        n_cpus: 1
        min_refine_buffer: 2000
        refine_buffer_frac_size: 5
        refine_pair_dist_frac_size: 2
        refine_bp_kernels: [0, 50, 500]
        refine_min_support: 2
        refine_disable: False
        min_pair_support: 2
        min_pair_distance: 4000
        max_pair_distance: 1000000
        scan_target_intervals: True
        stream: True
        view_mode: False
        store_img: False
        empty_annotation: False
        bins_per_block: 8000
        min_sv_len: 4000
        min_qual_score: 50
        bam_type: BAM_TYPE.SHORT
        signal_set: SV_SIGNAL_SET.SHORT
        signal_set_origin: SHORT
        bed: None
        blacklist_bed: None
        signal_vmax: {'RD': 600, 'RD_LOW': 800, 'RD_CLIPPED': 600, 'SM': 200, 'SR_RP': 600, 'LR': 600, 'LLRR': 100, 'RL': 100, 'LLRR_VS_LR': 1}
        signal_mapq: {'RD': 20, 'RD_LOW': 0, 'RD_CLIPPED': 20, 'SM': 20, 'SR_RP': 0, 'LR': 0, 'LLRR': 1, 'RL': 1, 'LLRR_VS_LR': 1}
        bin_size: 750
        interval_size: 150000
        step_size: 50000
        shift_size: None
        heatmap_dim: 1000
        image_dim: 256
        class_set: SV_CLASS_SET.BASIC5ZYG
        num_keypoints: 1
        bbox_padding: 0
        config_file: call_data.yaml
        dataset_dir: /share/home/yzbsl_masw/data/projects/results/CS2.1/AABBDD/SV_cue
        info_dir: /share/home/yzbsl_masw/data/projects/results/CS2.1/AABBDD/SV_cue/info/
        image_dir: /share/home/yzbsl_masw/data/projects/results/CS2.1/AABBDD/SV_cue/images/
        annotation_dir: /share/home/yzbsl_masw/data/projects/results/CS2.1/AABBDD/SV_cue/annotations/
        annotated_images_dir: /share/home/yzbsl_masw/data/projects/results/CS2.1/AABBDD/SV_cue/annotated_images/
        classes: ['NEG', 'DEL-HOM', 'INV-HOM', 'DUP-HOM', 'DEL-HET', 'INV-HET', 'DUP-HET', 'IDUP-HOM', 'IDUP-HET']
        num_classes: 9
        num_signals: 6
        uid: 0000000000
        log_file: /share/home/yzbsl_masw/data/projects/results/CS2.1/AABBDD/SV_cue/info/main.log
Traceback (most recent call last):
  File "/share/home/yzbsl_masw/scripts/cue/engine/call.py", line 96, in <module>
    chr_name_chunks, chr_names = seq_utils.partition_chrs(data_config.chr_names, data_config.fai, n_procs)
  File "/share/home/yzbsl_masw/scripts/cue/seq/utils.py", line 16, in partition_chrs
    random.shuffle(chr_names)
  File "/share/home/yzbsl_masw/.conda/envs/cue/lib/python3.8/random.py", line 307, in shuffle
    x[i], x[j] = x[j], x[i]
TypeError: 'str' object does not support item assignment
```

**Comment by jingydz** [comment]
Have you solved the problem？

results]$ python ../engine/call.py --data_config data.yaml --model_config model.yaml
Traceback (most recent call last):
  File "/xxx/software/cue/cue-master/results/../engine/call.py", line 23, in <module>
    import engine.config_utils as config_utils
ModuleNotFoundError: No module named 'engine'

**Comment by kuro7766** [comment]
I set PYTHONPATH and it solves this problem.
```
export PYTHONPATH=${PYTHONPATH}:/path/to/cue
```
