### ISSUE TITLE
add_by_signal function error when running call.py

### ISSUE THREAD

**Issue by bbunce** [PopicLab/cue#28]
Hi! I am running into an index error when running the call.py script. I am running this inside a docker container and had to update a couple of the packages in the requirements.txt file as I was receiving an error when trying to install pycocotools. The error and details of the config.yaml files used are below. Thanks in advance for your help.

```
Traceback (most recent call last):
  File "call.py", line 104, in <module>
    _ = Parallel(n_jobs=n_procs)(
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 252, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 252, in <listcomp>
    return [func(*args, **kwargs)
  File "call.py", line 82, in call
    aln_index = AlnIndex.generate_or_load(chr_name, data_config)
  File "/cue/cue/seq/aln_index.py", line 308, in generate_or_load
    return AlnIndex.generate(chr_name, data_config)
  File "/cue/cue/seq/aln_index.py", line 77, in generate
    aux_index.add(read)
  File "/cue/cue/seq/aln_index.py", line 92, in add
    self.add_by_signal(read, signal, bin_id, rp_type)
  File "/cue/cue/seq/aln_index.py", line 156, in add_by_signal
    self.bins[signal][bin_id] += 1
IndexError: list index out of range
```

```
[INFO]  ========== Model config ==========
        model_path: ../data/demo/models/cue.pt
        n_cpus: 1
        gpu_ids: []
        batch_size: 16
        logging_level: INFO
        report_interval: 50
        n_jobs_per_gpu: 1
        signal_set: SV_SIGNAL_SET.SHORT
        class_set: SV_CLASS_SET.BASIC5ZYG
        num_keypoints: 1
        model_architecture: HG
        image_dim: 256
        sigma: 10
        stride: 4
        heatmap_peak_threshold: 0.4
        pretrained_refinenn_path: None
        config_file: ../data/demo/config/model.yaml
        experiment_dir: /cue/cue/data/demo/config
        devices: [device(type='cpu')]
        device: cpu
        log_dir: /cue/cue/data/demo/config/logs/
        report_dir: /cue/cue/data/demo/config/reports/
        log_file: /cue/cue/data/demo/config/logs/main.log
        classes: ['NEG', 'DEL-HOM', 'INV-HOM', 'DUP-HOM', 'DEL-HET', 'INV-HET', 'DUP-HET', 'IDUP-HOM', 'IDUP-HET']
        num_classes: 9
        n_signals: 6
[INFO] ========== Data config =========
        bam: ../data/demo/inputs/TwEx_EX2113470.bam
        fai: ../data/demo/inputs/Homo_sapiens.GRCh38.dna.primary_assembly.fa.fai
        chr_names: ['4']
        n_cpus: 1
        logging_level: INFO
        min_refine_buffer: 2000
        refine_buffer_frac_size: 5
        refine_pair_dist_frac_size: 2
        refine_bp_kernels: [0, 50, 500]
        refine_min_support: 2
        refine_disable: False
        min_pair_support: 2
        min_pair_distance: 4000
        max_pair_distance: 1000000
        scan_target_intervals: True
        stream: True
        view_mode: False
        store_img: False
        empty_annotation: False
        bins_per_block: 8000
        min_sv_len: 4000
        min_qual_score: 50
        bam_type: BAM_TYPE.SHORT
        signal_set: SV_SIGNAL_SET.SHORT
        signal_set_origin: SHORT
        bed: None
        blacklist_bed: None
        signal_vmax: {'RD': 600, 'RD_LOW': 800, 'RD_CLIPPED': 600, 'SM': 200, 'SR_RP': 600, 'LR': 600, 'LLRR': 100, 'RL': 100, 'LLRR_VS_LR': 1}
        signal_mapq: {'RD': 20, 'RD_LOW': 0, 'RD_CLIPPED': 20, 'SM': 20, 'SR_RP': 0, 'LR': 0, 'LLRR': 1, 'RL': 1, 'LLRR_VS_LR': 1}
        bin_size: 750
        interval_size: 150000
        step_size: 50000
        shift_size: None
        heatmap_dim: 1000
        image_dim: 256
        class_set: SV_CLASS_SET.BASIC5ZYG
        num_keypoints: 1
        bbox_padding: 0
        config_file: ../data/demo/config/data.yaml
        dataset_dir: /cue/cue/data/demo/config
        info_dir: /cue/cue/data/demo/config/info/
        image_dir: /cue/cue/data/demo/config/images/
        annotation_dir: /cue/cue/data/demo/config/annotations/
        annotated_images_dir: /cue/cue/data/demo/config/annotated_images/
        classes: ['NEG', 'DEL-HOM', 'INV-HOM', 'DUP-HOM', 'DEL-HET', 'INV-HET', 'DUP-HET', 'IDUP-HOM', 'IDUP-HET']
        num_classes: 9
        num_signals: 6
        uid: 0000000000
        log_file: /cue/cue/data/demo/config/info/main.log
```

**Comment by viq854** [comment]
Hi @bbunce,

This could happen if the reads were mapped to a different reference than the one provided in the "fai" field. Could you please check the header of the BAM file? 

Thanks,
Victoria

**Comment by bbunce** [comment]
Hi Victoria, apologies my mistake entirely. I had different builds for BAM/REF. Fixed when I ran with correct files.
